version: '3.5'

services:
  db:
    container_name: arvan-db
    image: postgres
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: 'arvan'
      PGDATA: '/data/postgres'
    volumes:
       - "./db-data:/data/postgres"
    ports:
      - "5444:5432"
    restart: always
  
  wallet:
    container_name: arvan_wallet
    image: wallet
    depends_on:
      - "db"
    environment:
      DB_HOST: 'db'
      DB_PORT: 5432
    ports:
      - "8081:8080"

  voucher:
    container_name: arvan_voucher
    image: voucher
    depends_on:
      - "db"
    environment:
      DB_HOST: 'db'
      DB_PORT: 5432
    ports:
      - "8082:8080"
